site_name: Rankify Documentation
site_url: https://rankify.it
repo_url: https://github.com/rankify-it
site_description: Rankify documentation portal
theme:
  name: readthedocs
  #   name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  hljs_languages:
    - solidity
    - typescript
    - rust
    - bash
plugins:
  - search
  - plantuml:
      theme: cyborg
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"