site_name: Peeramid Labs Documentation
site_url: https://rankify.it
repo_url: https://github.com/peeramid-labs
site_description: Rankify documentation portal
nav:
    - Welcome:
          - "index.md"
          - "governance.md"
          - "tokens.md"
    - Developing:
          - "architecture/index.md"
          - "architecture/create.md"
        #   - "architecture/specifications.md"
    - interfaces:
          - ...
    - Support:
          - "support/index.md"
          - "support/faq.md"
theme:
    name: readthedocs
    #   name: mkdocs
    color_mode: dark
    user_color_mode_toggle: true
    hljs_languages:
        - solidity
        - typescript
        - rust
        - bash
plugins:
    - awesome-pages
    - mermaid2:
          version: "9.4.3" # only works with version < 10
          #   arguments:
          #       theme: "dark"
          #       themeVariables:
          #           primaryColor: "#BB2528"
          #           primaryTextColor: "#fff"
          #           primaryBorderColor: "#7C0000"
          #           lineColor: "#F8B229"
          #           secondaryColor: "#20000F"
          #           tertiaryColor: "#fff"
    - search
    - plantuml:
          theme: cyborg
          puml_url: https://www.plantuml.com/plantuml/
          num_workers: 8
markdown_extensions:
    - admonition
    - mkautodoc
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - toc:
          permalink: "#"
extra_css:
    - css/custom.css
# nav:
#     - Home: "Welcome/index.md"
