name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
        - uses: './.github/setup'
        - name: Copy docs
          run: ./copy-contract-docs.sh
        - name: Deploy docs
          run: ./deploy-docs.sh
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CUSTOM_DOMAIN: docs.rankify.it
            CONFIG_FILE: mkdocs.yml
            EXTRA_PACKAGES: build-base
            # GITHUB_DOMAIN: github.myenterprise.com
            REQUIREMENTS: requirements.txt